#!/usr/bin/env python3
"""Generate drivers/media/i2c/hi1337_tables.h from the stock SM-X800 CamX decode.

Reads the decoded Hynix Hi1337 register lists (one register per line,
"0xADDR 0xVALUE at=2 dt=2 WRITE delay=0us") for the shared init table and the
three 30 fps modes, and writes the C header the hi1337 driver includes.

Inputs (default: /home/aaron/src/sm8450-camera-ref/vendor/decoded/):
  com.samsung.sensormodule.1_hynix_hi1337_front.init0.regs.txt   init (all modules)
  com.samsung.sensormodule.1_hynix_hi1337_front.mode0.regs.txt   2032x1524 @30
  com.samsung.sensormodule.12_hynix_hi1337_front_full.mode0.regs.txt  4000x3000 @30
  com.samsung.sensormodule.0_hynix_hi1337.mode0.regs.txt          4128x3096 @30

Output (default: patch-work/linux-7.2/drivers/media/i2c/hi1337_tables.h).

Mode-select writes (0x0b00) are dropped; the driver starts and stops the stream
itself. Every other register is kept in file order. A byte-wide entry (dt=1)
aborts the run, since the driver's table writer is 16-bit only.

Usage: hi1337-tables.py [DECODED_DIR] [OUTPUT_HEADER]
"""

import os
import sys

REG_MODE_SELECT = 0x0B00

DEFAULT_SRC = "/home/aaron/src/sm8450-camera-ref/vendor/decoded"
DEFAULT_OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..",
    "patch-work", "linux-7.2", "drivers", "media", "i2c", "hi1337_tables.h")

TABLES = [
    ("hi1337_init_regs",
     "com.samsung.sensormodule.1_hynix_hi1337_front.init0.regs.txt",
     "Sensor initialisation, shared by all SM-X800 Hi1337 modules"),
    ("hi1337_mode_2032x1524_regs",
     "com.samsung.sensormodule.1_hynix_hi1337_front.mode0.regs.txt",
     "2032x1524 @ 30 fps, 2x2 binned (front module default)"),
    ("hi1337_mode_4000x3000_regs",
     "com.samsung.sensormodule.12_hynix_hi1337_front_full.mode0.regs.txt",
     "4000x3000 @ 30 fps, full resolution (front module)"),
    ("hi1337_mode_4128x3096_regs",
     "com.samsung.sensormodule.0_hynix_hi1337.mode0.regs.txt",
     "4128x3096 @ 30 fps, full resolution (rear main module)"),
]


def parse(path):
    regs = []
    dropped = 0
    with open(path) as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line.startswith("0x"):
                continue
            fields = line.split()
            addr = int(fields[0], 16)
            val = int(fields[1], 16)
            opts = dict(f.split("=", 1) for f in fields[2:] if "=" in f)
            if opts.get("dt", "2") != "2":
                sys.exit(f"{path}:{lineno}: dt={opts['dt']} entry "
                         f"at 0x{addr:04x}; only 16-bit writes are supported")
            if opts.get("at", "2") != "2":
                sys.exit(f"{path}:{lineno}: at={opts['at']} entry "
                         f"at 0x{addr:04x}; only 16-bit addresses are supported")
            if opts.get("delay", "0us") not in ("0", "0us"):
                sys.exit(f"{path}:{lineno}: delay={opts['delay']} at "
                         f"0x{addr:04x}; the table writer has no delays")
            if addr == REG_MODE_SELECT:
                dropped += 1
                continue
            regs.append((addr, val))
    return regs, dropped


def emit(out, name, comment, regs):
    out.write(f"/* {comment} */\n")
    out.write(f"static const struct hi1337_reg {name}[] = {{\n")
    for i in range(0, len(regs), 2):
        pair = regs[i:i + 2]
        out.write("\t" + " ".join(f"{{ 0x{a:04x}, 0x{v:04x} }},"
                                  for a, v in pair) + "\n")
    out.write("};\n\n")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    dst = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    dst = os.path.normpath(dst)

    with open(dst, "w") as out:
        out.write("/* SPDX-License-Identifier: GPL-2.0 */\n")
        out.write("/*\n"
                  " * Hynix Hi1337 register tables, taken from the Samsung "
                  "SM-X800 (Galaxy Tab S8+)\n"
                  " * stock camera configuration.\n"
                  " *\n"
                  " * Generated by tools/hi1337-tables.py; do not edit by "
                  "hand.\n"
                  " */\n\n")
        out.write("#ifndef __HI1337_TABLES_H__\n#define __HI1337_TABLES_H__\n\n")
        out.write("#include <linux/types.h>\n\n")
        out.write("struct hi1337_reg {\n\tu16 address;\n\tu16 val;\n};\n\n")
        for name, fname, comment in TABLES:
            regs, dropped = parse(os.path.join(src, fname))
            emit(out, name, comment, regs)
            print(f"{name}: {len(regs)} regs from {fname}"
                  + (f" ({dropped} mode-select entries dropped)"
                     if dropped else ""))
        out.write("#endif /* __HI1337_TABLES_H__ */\n")
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
